Changed the app logo (favicon)  #103
zeforgezenica/busez pull request #110
Opened 2024-10-15 08:12 UTC by Scharfcsh

Replaced the default  favicon.ico in "frontend/src/app" logo to icon.png(it's the same image given ZebusezLogo.png).
And deleted vercels and next defaults icons.

![Screenshot 2024-10-15 134148](https://github.com/user-attachments/assets/e413f75f-09c4-4d16-8dfc-e7506db4b4db)

2024-10-16 19:25 UTC, bambooch requested changes
Thanks for opening a PR!

First of all kudos to translating some stuff into bosnian, but just for future reference we all understand english :D Also thanks for taking time to try to tackle all these issues.

Now to the feedback. There are a few general points and code specific ones you can find in the code sections below. 

1. The image below shows my result after spinning up your PR. The default mode is light (no problem there) but the integration of the other components (for example the footer) or the datepicker text isn't complete. Be sure to watch out for merging of #108 and #109 (should happen in the next hour or so) so then it won't be necessary to style that MUI date picker text that is in your version. This light mode is unnacceptable of course so changes are required at least for that. 

2, Please create a new branch on your fork when opening a PR so maintainers and other contributors can add commits to the PR. This will also enable the possibility of doing 3.

3. Opening a 1 PR for two existing issues isn't best practice since I can't merge only the icon for example. Opening two PRs would be much better. 

All in all, I'd suggest you scratch this PR and open new ones while implementing the feedback I left for you in this, as well as in the code comments below.

The image referenced by 1.

![image](https://github.com/user-attachments/assets/c19772e6-9b7d-414f-aeab-f11e7a8bcf11)


Once more, thanks for taking the time to make a contribution! Looking forward to the corrections!

2024-10-16 19:25 UTC, bambooch commented on .gitignore
> +.env.local
These are unecessary because of line 30 below

2024-10-16 19:25 UTC, bambooch commented on frontend/src/app/page.tsx
the changes to this file all seem to be related to code formating

we don't have a strict ruleset for formatting yet but just for your reference this would ideally go into another commit instead of this one which points to just an icon change

no changes needed

2024-10-16 19:25 UTC, bambooch commented on frontend/src/app/layout.tsx
> +
why the extra line here?

2024-10-16 19:25 UTC, bambooch commented on frontend/src/app/page.tsx
from the second commit I see a complete replacement of the file which doesn't at all indicate what specifically was changed, formatting specific parts is not problematic like in the previous commit but this is now more difficult to review since everything is marked as changed..

2024-10-16 19:25 UTC, bambooch commented on frontend/src/app/routes/RouteSearch.tsx
the same comment as the 2nd comment for RouteSearch.tsx

2024-10-17 16:17 UTC, Scharfcsh commented on frontend/src/app/layout.tsx
> +
It's because of my IDEs formatter , and I completely missed out that part. I'll keep that in mind from now on.

2024-10-17 16:21 UTC, Scharfcsh commented on frontend/src/app/page.tsx
Shadcn documentation suggested to use <ThemeProvider>and keep children inside it.
So I wrapped  <Provider> inside <themeProvider>.

2024-10-17 16:27 UTC, Scharfcsh commented on frontend/src/app/routes/RouteSearch.tsx
thank you for feedback. I will make sure to avoid these unnecessary changes.

2024-10-17 16:51 UTC, closed without merging