Feat Convert Homepage buttons to shadcn/ui
zeforgezenica/busez pull request #117
Opened 2024-10-16 23:36 UTC by Cormwww

Hello, sorry about the confusion with the other PR but I think that this should now work. I added Shadcn/ui to the repository and added the buttons to the page.tsx file in the repository please tell me if there are ant issues with it. Thanks!

2024-10-18 15:58 UTC, nine-codes commented
Ovo treba zatvoriti @alempasalic @bambooch

2024-10-19 20:50 UTC, bambooch commented
Hey @Cormwww I've just tested your fork and it seems it doesn't work, see screenshot below, this is after running `pnpm turbo install` and `pnpm turbo dev` from the root directory 

also I believe that shadcn was correctly configured as part of #79 please take a look at that and at PRs such as #85 to see how to correctly add shadcn components to the repo

![image](https://github.com/user-attachments/assets/9ab781b1-7d22-4e26-9a98-935666b74b14)

2024-10-19 20:53 UTC, bambooch requested changes
Too much code has been deleted here for a button switch. Once more, please understand the requirements and then write the code. If you need clarification, please let me know what is confusing you.

2024-10-19 20:53 UTC, bambooch commented on frontend/src/app/page.tsx
> +        const fetchedAgency = await AgencyService.getAgency(id as string);
you seem to be adding this agency/city functionality as part of your PRs that should just change the buttons on the homepage. please make sure you understand the requirements before opening any PRs

2024-10-20 05:19 UTC, bambooch commented
@Cormwww I see that you pushed some commit in the last hour but did not address the comments above. Please consider them and let us know if you need support.

2024-10-22 20:45 UTC, closed without merging